name: jest-and-docker-ci

# on:
#   push:
#     branches:
#       - main

on: pull_request

jobs:
  integration-test:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v2
      - name: Create Dotenv File
        uses: actually-colab/github-action-create-env-file@v2.3
        with:
          envkey_NODE_ENV: "development"
          envkey_SERVER_HOST: "localhost"
          envkey_SERVER_PORT: "4000"
          envkey_DB_HOST: "db"
          directory: server
          file_name: .env
      - name: Run integration test
        run: npm i -g pnpm && pnpm run integration-test

  build:
    needs: integration-test
    runs-on: ubuntu-latest
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ vars.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          push: true
          context: "{{defaultContext}}:server"
          tags: ${{ vars.DOCKERHUB_USERNAME }}/2209-wns-adleman-citycompass:latest
