name: integration

on: pull_request

jobs:
  integration-test:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v2
      - name: Clean cache
        run: npm cache clean --force
      - name: Run integration test
        run: npm i -g pnpm && pnpm run integration-test
